version: '3'
services:
  web-app:
    build: app
    volumes:
      - staticfiles_volume:/opt/app/static/
    expose:
      - "8000"
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - staticfiles_volume:/var/www/data/static
    depends_on:
      - web-app
    ports:
      - "80:80"

  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    env_file: ./app/.env
    ports:
      - '5432:5432'
    volumes: 
      - postgres_db_volume:/var/lib/postgresql/data
    

volumes:
  postgres_db_volume:
  staticfiles_volume: