version: '3'
services:
  web-app:
    build:
      context: './movies_admin'
      target: "production"
    volumes:
      - staticfiles_volume:/opt/app/static/
    expose:
      - "8000"
    env_file: ./movies_admin/.env
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site-configs:/etc/nginx/conf.d:ro
      - staticfiles_volume:/var/www/data/static
    depends_on:
      - web-app
    ports:
      - "80:80"

  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    env_file: .pg_env
    expose:
      - "5432"
    volumes: 
      - postgres_db_volume:/var/lib/postgresql/data
    

volumes:
  postgres_db_volume:
  staticfiles_volume: