# Generated by Django 3.2 on 2023-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv-show', 'TV-Show')], max_length=25, verbose_name='type'),
        ),
    ]
